### ISSUE TITLE
Please support IPv6

### ISSUE THREAD

**Issue by kseistrup** [xyproto/http2check#1]
It doesn't seem like `http2check` supports IPv6.

**Comment by xyproto** [comment]
Thanks for the feature request! I'll look into it.

**Comment by kseistrup** [comment]
:smile:

**Comment by xyproto** [comment]
It works for IPv6 addresses here now. Please test.

**Comment by kseistrup** [comment]
It seems to prefer IPv4 over IPv6 if the host is dual stacked (even when `/etc/gai.conf` tells it not to).  I don't have access to logs on an IPv6 only host.

**Comment by kseistrup** [comment]
But I can edit `/etc/hosts` so as to lie to `http2check` about remote's IP address, and if it has no choice but IPv6 it works fine.

**Comment by xyproto** [comment]
I see. Thanks for the info. Do you know how `http2check` could use the right type of address (IPv4 vs IPv6), given a hostname?

**Comment by xyproto** [comment]
I guess I could add a flag. /etc/gai.conf doesn't sound cross-platform.

**Comment by kseistrup** [comment]
I don't know how [Go](https://golang.org/) generally implements [`getaddrinfo(3)`](http://linux.die.net/man/5/gai.conf) / [RFC 3484](https://www.ietf.org/rfc/rfc3484.txt), but already in 2011  ([r57](https://golang.org/doc/devel/release.html#r57)) it seems that [`LookupHost`](https://golang.org/pkg/net/#LookupHost) …

> […] now uses [`cgo`](https://golang.org/cmd/cgo/) to implement network name lookups using the C library getaddrinfo(3) function when possible. This ensures that Go and C programs resolve names the same way and also avoids the OS X application-level firewall.

If you for some reason cannot use `LookupHost` (or if you're already using that function and it performs the way that made me open this issue), then I would prefer `http2check` to do whatever it does now without any switches, and then have you implement a `-4`/`--ipv4` and a `-6`/`--ipv6` switch so that it's possible to force a certain protocol.

Cheers.

**Comment by xyproto** [comment]
Think I will postpone this one until IPv6 is even better supported by Go, so that no flags are needed.

**Comment by kseistrup** [comment]
So, let me understand this: Did you close the issue because IPv6 is now supported or because you prefer to keep the issue in your head “until IPv6 is even better supported by Go” rather than having Github remind you that there is an IPv6 issue?

**Comment by xyproto** [comment]
Yes, the second one. I'm conflicted if I should develop further on `http2check` or not.

There are [so many](https://blog.cloudflare.com/tools-for-debugging-testing-and-using-http-2/) alternative HTTP/2 check utilities out, many with wide support in most distros, like curl. [h2c](https://github.com/fstab/h2c) is also written in Go and looks powerful (but perhaps not as minimalistic and brief).

However, if you think `http2check` might still be useful, that would be enough encouragement for me to actually implement the IPv6 support. :)

**Comment by kseistrup** [comment]
In my opinion: If you intend to keep developing http2check this issue should remain open (since it hasn't been resolved). If you do not wish to spend more time on http2check, which would be fair enough, it doesn't matter whether this issue is open or closed, but you should probably leave a note at the top of the project page saying that the project has been abandoned.

Originally, I installed http2check because I set up [Caddy](https://caddyserver.com/) to serve pages on a dual-stack box and needed a tool to, well, check HTTP/2. Since http2check didn't support IPv6 I ended up using another tool, and now that I have checked that Caddy actually uses HTTP/2 I don't need a tool at all.

I guess what I'm trying to say here is: I think it's wrong to close the issue since the issue hasn't been resolved. If other potential users pass by they might get the impression that http2check actually supports IPv6 because the issue has been closed — and somebody might even reopen the issue because they experience the missing support for IPv6, thus wasting your and their own time.

It's not shameful to have open issues on a project, methinks, but it would be more correct to either leave the issue open or label it as “wontfix”.

**Comment by xyproto** [comment]
I agree with everything you're saying. I'll just leave this issue open, mainly as an indication that it is an unresolved issue. Thanks for the input.

**Comment by xyproto** [comment]
Added to the documentation that IPv6 addresses are not supported.

There are many available utilities out there by now, that can do this.
